name: Deploy para Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy no Railway
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Deploy no Railway
        uses: railway-app/actions-deploy@v1
        with:
          token: ${{ secrets.RAILWAY_TOKEN }}
          service: conversor-medidas
